### ISSUE TITLE
Skapa och designa välkomstsegmentet (delen ovanför todo-listan) med tid, veckodag och datum presenteras. (G)

### ISSUE THREAD

**Issue by MimPMC** [plugga-tech/kalenderverktyg-med-javascript-jesper-yehad-mimmi-linus-ham#6]

**Comment by Lvl1Pichu** [comment]
Har skrivit Script för att hämta tid i timmar, minuter, sekunder.
Samt hämta datum i dag, månad, år. Uppdateras varje sekund. Kan dock optimeras lite, eventuellt separera klockan från datum-funktionen. :)
